/* $Revision: 1.1 $ */
// firstapp.cpp
// Automatically generated by Matlab AppWizard version 1.0
//
// This is the gateway routine for a MATLAB Math/Graphics Library-based
// C MATLAB MEX File.


#include "mex.h"
#include "CRemoveBridges.h"

void mexFunction( int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[] ){
  unsigned char *resultData;
  unsigned char *preSegData;
  unsigned char *unSegData;
  
  const int *dims;
  
  float	averageWhiteIntensity;
  float	thresholdIntensity;
  float	averageGrayIntensity;
  
  if (nrhs!=5) {
    mexErrMsgTxt("5 inputs required.");
  } else if (nlhs>1) {
    mexErrMsgTxt("Too many output arguments.");
  }
  
  //plhs[0]= mxCreateDoubleMatrix(mrows,ncols,mxREAL);

  preSegData = (unsigned char*)mxGetPr(prhs[0]);
  unSegData = (unsigned char*)mxGetPr(prhs[1]);
  averageWhiteIntensity = (float)mxGetScalar(prhs[2]);
  thresholdIntensity = (float)mxGetScalar(prhs[3]);
  averageGrayIntensity = (float)mxGetScalar(prhs[4]);

  dims = mxGetDimensions(prhs[0]);

  plhs[0] = mxCreateNumericArray(3,dims,mxUINT8_CLASS,mxREAL);
  resultData = (unsigned char *)mxGetPr(plhs[0]);

  CRemoveBridges *bro = new CRemoveBridges();

  bro->remove(preSegData,unSegData, resultData, dims[0],dims[1],dims[2],
	     averageWhiteIntensity,thresholdIntensity,averageGrayIntensity);

}

