function startup

fprintf('(c) Jan Modersitzki 2006/03/17\n');
folder = {fullfile(pwd,'WBIR-2006'),...
    fullfile(pwd,'devel'),...
    fullfile(pwd,'exp-hands'),...
    fullfile(pwd,'exp-mice'),...
    fullfile(pwd,'exp-MRI'),...
    fullfile(pwd,'RIC'),...
    fullfile(pwd,'FLIRT2D'),...
    fullfile(pwd,'solvers')};

folder = {fullfile(pwd,'WBIR-2006'),...
    fullfile(pwd,'exp-hands'),...
    fullfile(pwd,'exp-mice'),...
    fullfile(pwd,'exp-MRI'),...
    fullfile(pwd,'FLIRT2D'),...
    fullfile(pwd,'interpolation'),...
    fullfile(pwd,'solvers')};

for j=1:length(folder),
  fprintf('addpath(''%s'')\n',folder{j});
  addpath(folder{j})
end;
return;
%--------------------------------------------------------------------