function this = addStatisticHeader(this,agg_name,local_name, ile, icpp, ivs, uid)

if nargin == 3
    if( isempty(this.pathway_statistic_headers) )
        this.pathway_statistic_headers = struct('is_luminance_encoding',1,...
            'is_computed_per_point',1,...
            'is_viewable_stat',1,...
            'aggregate_name',agg_name,...
            'local_name',local_name,...
            'unique_id', 1);
    else

        this.pathway_statistic_headers(end+1) = struct('is_luminance_encoding',1,...
            'is_computed_per_point',1,...
            'is_viewable_stat',1,...
            'aggregate_name',agg_name,...
            'local_name',local_name,...
            'unique_id', 1);
    end
elseif nargin == 7
    if( isempty(this.pathway_statistic_headers) )
        this.pathway_statistic_headers = struct('is_luminance_encoding',ile,...
            'is_computed_per_point',icpp,...
            'is_viewable_stat',ivs,...
            'aggregate_name',agg_name,...
            'local_name',local_name,...
            'unique_id', uid);
    else

        this.pathway_statistic_headers(end+1) = struct('is_luminance_encoding',ile,...
            'is_computed_per_point',icpp,...
            'is_viewable_stat',ivs,...
            'aggregate_name',agg_name,...
            'local_name',local_name,...
            'unique_id', uid);
    end

else
    disp('Error using addStatistic');
end